query Weather($tournamentId: ID!) {
  weather(tournamentId: $tournamentId) {
    title
    hourly {
      title
      condition
      windDirection
      windSpeedKPH
      windSpeedMPH
      humidity
      precipitation
      temperature {
        ... on StandardWeatherTemp {
          __typename
          tempC
          tempF
        }
        ... on RangeWeatherTemp {
          __typename
          minTempC
          minTempF
          maxTempC
          maxTempF
        }
      }
    }
    daily {
      title
      condition
      windDirection
      windSpeedKPH
      windSpeedMPH
      humidity
      precipitation
      temperature {
        ... on StandardWeatherTemp {
          __typename
          tempC
          tempF
        }
        ... on RangeWeatherTemp {
          __typename
          minTempC
          minTempF
          maxTempC
          maxTempF
        }
      }
    }
  }
}
