"""Refresh STAT_IDS from the live StatOverview GraphQL operation.

Adapted from WalrusQuant/pgatourPY under its preserved MIT license.

    python scripts/refresh_stat_ids.py

Writes src/pga_tour_api/stat_ids.py. Requires network access.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from pga_tour_api._api import graphql_request  # noqa: E402

OUT = ROOT / "src" / "pga_tour_api" / "stat_ids.py"


def main() -> None:
    data = graphql_request("StatOverview", {"tourCode": "R", "year": 2026})
    overview = data.get("statOverview") or {}
    rows: list[tuple[str, str, str, str]] = []
    seen: set[str] = set()
    for cat in overview.get("categories") or []:
        category = cat.get("displayName") or cat.get("category") or ""
        for sub in cat.get("subCategories") or []:
            subcategory = sub.get("displayName") or ""
            for st in sub.get("stats") or []:
                sid = st.get("statId")
                name = st.get("statTitle") or ""
                if not sid or sid in seen:
                    continue
                seen.add(sid)
                rows.append((sid, name, category, subcategory))

    if not rows:
        raise SystemExit("StatOverview returned no stats")

    lines = [
        '"""PGA Tour stat ID lookup table.',
        "",
        "Adapted from WalrusQuant/pgatourPY under the MIT license preserved in",
        "``LICENSES/pgatourPY-MIT.txt``.",
        "",
        "Regenerated by ``scripts/refresh_stat_ids.py`` from the live",
        "``StatOverview`` GraphQL operation. Do not edit by hand.",
        '"""',
        "import pandas as pd",
        "",
        "STAT_IDS = pd.DataFrame([",
    ]
    for sid, name, category, subcategory in rows:
        def q(s: str) -> str:
            return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

        lines.append(
            "    {"
            f'"stat_id": {q(sid)}, '
            f'"stat_name": {q(name)}, '
            f'"category": {q(category)}, '
            f'"subcategory": {q(subcategory)}'
            "},"
        )
    lines.append("])")
    lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"Wrote {len(rows)} stat IDs to {OUT}")


if __name__ == "__main__":
    main()
